global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: /metrics 
    static_configs:
      - targets: ['fastapi_app:8000'] 